### ISSUE TITLE
Check: README: Check stable tags (they should match the version and NOT be trunk)

### ISSUE THREAD

**Issue by davidperezgar** [WordPress/plugin-check-legacy#6] opened 2023-05-08 15:25 UTC

**Comment by dd32** [comment] 2023-05-10 02:33
Duplicate of #3 I think, but this is handled by https://github.com/WordPress/plugin-check/blob/54f1eb0142905bf03f80459ea5668d559fad233d/checks/readme.php#L73-L100

**Closed as completed by dd32** 2023-05-10 02:33 UTC
